<div style="background-color:#000; font-size: 8pt; padding-top: 5px;" class="tip">
	<div style="background-image: url('images/go.gif'); background-repeat: no-repeat; height:15px; margin-left:8px; padding-top: 2px; margin-bottom: 5px;">
		<a href="#" style="color: #FFF; text-decoration: none; padding-left: 22px;">Jogos de hoje</a>
	</div>
	<img src="images/tip-bsq.gif" style="margin-bottom: 5px;" width="150"><br>
	<div style="background-image: url('images/go.gif'); background-repeat: no-repeat; height:15px; margin-left:8px; padding-top: 2px; margin-bottom: 5px;">
		<a href="#" style="color: #FFF; text-decoration: none; padding-left: 22px;">NBA</a>
	</div>
	<div style="background-image: url('images/go.gif'); background-repeat: no-repeat; height:15px; margin-left:8px; padding-top: 2px; margin-bottom: 5px;">
		<a href="#" style="color: #FFF; text-decoration: none; padding-left: 22px;">Liga Brasileira</a>
	</div>
</div>